# Generated by Django 5.1.7 on 2025-03-15 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pyuser',
            old_name='password_salt',
            new_name='password',
        ),
    ]
