# Generated by Django 5.1.7 on 2025-03-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_pyuser_options_alter_pyuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='note',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
